### ISSUE TITLE
Kanban Board for Application

### ISSUE THREAD

**Issue by t-bello7** [t-bello7/hotel-frontend#10]
This is the link to the kanban board for final capstone project
![Screenshot from 2023-01-12 15-38-42](https://user-images.githubusercontent.com/24270269/212095586-362d3d8c-2946-4d29-b6b4-0098d29e3fe3.png)- https://github.com/users/t-bello7/projects/2/views/1
The project consists of 4 members.

**Comment by Meltrust** [comment]
Hi @t-bello7,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that contains no screenshot of your kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by t-bello7** [comment]
@Meltrust Thank you for the review.

**Comment by Meltrust** [comment]
Hi @t-bello7,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [x] Kindly, please add descriptions for all your cards, as stated in the project requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vichuge** [comment]
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
